version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev -- --webpack -H 0.0.0.0

  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # CHANGEMENT ICI : Port 6543 + PgBouncer pour passer les pare-feu
      - DATABASE_URL=postgresql://fraid:password@db:5432/portfolio_db
    # On garde depends_on pour la forme, mais le backend ignorera la db locale
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=fraid
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data: